// supabase/functions/_shared/errors.ts
export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE: 'DUPLICATE',
  ACCOUNT_ARCHIVED: 'ACCOUNT_ARCHIVED',
  ACTIVE_LOAN_EXISTS: 'ACTIVE_LOAN_EXISTS',
  ACCOUNT_UPGRADE_NOT_VERIFIED: 'ACCOUNT_UPGRADE_NOT_VERIFIED',
  INVALID_STATUS: 'INVALID_STATUS',
  PAYMENT_ALREADY_MADE: 'PAYMENT_ALREADY_MADE',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVER_ERROR: 'SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];