-- =====================================================================
-- Jireta Loans & Credit Corp 1966
-- Migration : 00139_seed_overdue_lender.sql
-- Purpose   : (REMOVED) This migration used to seed a demo "Overdue Lender"
--             test account (phone 09171234567, email overdue.lender@jireta.temp)
--             plus an overdue weekly loan, its schedules, a disbursement and a
--             20% penalty, so the Head Manager / Employee could inspect the
--             overdue + penalty flow.
--
--             The test account has been removed per request. On an
--             already-provisioned database the rows it created are deleted by
--             migration 00168_remove_views_and_test_account.sql.
--
--             This file is now intentionally a no-op so a fresh
--             `supabase db reset` never recreates the test data. The filename
--             / version is kept so the local migration history still lines up
--             with what has already been applied remotely.
-- =====================================================================

-- (no-op — see header)
